message(STATUS "Codecoverage -                     YES ")
if (CMAKE_COMPILER_IS_GNUCC)
    if(ENABLE_CODE_COVERAGE)
        SET(CODE_COVERAGE_COMPILE_FLAGS "-g -O0 -fprofile-arcs -ftest-coverage")
        SET(CODE_COVERAGE_LINK_FLAGS    "-lgcov")
        SET( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} ${CODE_COVERAGE_COMPILE_FLAGS}" )
        SET( CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} ${CODE_COVERAGE_LINK_FLAGS}" )
    endif()
endif()